/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\gbaman\gbtd\s_ball_map_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define superMapWidth 20
#define superMapHeight 18
#define superMapBank 0

extern unsigned char superMap[];

/* End of MAP.H */
